
translations_file_menu = {
    "en": {
        "title": "Encryption/Decryption Tool",
        "text_label": "Enter Text:",
        "encryption_method_label": "Select Encryption Method:",
        "key_label": "Enter Key (Number):",
        "random_button_text": "Generate Random Key",
        "output_label": "Output:",
        "encrypt_button": "Encrypt",
        "decrypt_button": "Decrypt",
        "file_encryption_decryption_tool_title": "File Encryption/Decryption Tool",
        "select_file_label": "Select File:",
        "browse_button_text": "Browse",
        "select_encryption_method_label": "Select Encryption Method:",
        "enter_key_label": "Enter Key (Number):",
        "generate_random_key": "Generate Random Key",
        "save_file_title": "Save File",
        "file_processed_success": "File processed and saved successfully!",
        "error": "Error",
        "unknown_method_error": "Unknown method.",
        "key_is_digit_error": "Key must be a number.",
        "no_file_selected": "No file selected.",
        "your_key": "Your key is: ",
        "browse_file_title": "Select File",
        "an_error_occurred": "An error occurred",
    },
    "az": {
        "title": "Şifreleme/Şifrə Açma Aləti",
        "text_label": "Mətn daxil edin:",
        "encryption_method_label": "Şifrələmə Metodunu Seçin:",
        "key_label": "Açar Daxil Edin (Rəqəm):",
        "random_button_text": "Təsadüfi Açar Yarat",
        "output_label": "Çıxış:",
        "encrypt_button": "Şifrələmək",
        "decrypt_button": "Şifrəni Aç",
        "file_encryption_decryption_tool_title": "Fayl Şifrələmə/Şifrə Açma Aləti",
        "select_file_label": "Fayl Seçin:",
        "browse_button_text": "Gözət",
        "select_encryption_method_label": "Şifrələmə Metodunu Seçin:",
        "enter_key_label": "Açar Daxil Edin (Rəqəm):",
        "generate_random_key": "Təsadüfi Açar Yarat",
        "save_file_title": "Faylı Saxla",
        "file_processed_success": "Fayl uğurla işlənib saxlanıldı!",
        "error": "Xəta",
        "unknown_method_error": "Bilinməyən metod.",
        "key_is_digit_error": "Açar bir rəqəm olmalıdır.",
        "no_file_selected": "Heç bir fayl seçilməyib.",
        "your_key": "Açarınız: ",
        "browse_file_title": "Fayl Seç",
        "an_error_occurred": "Bir xəta baş verdi"
    },
    "ru": {
        "title": "Инструмент для шифрования/расшифровки",
        "text_label": "Введите текст:",
        "encryption_method_label": "Выберите метод шифрования:",
        "key_label": "Введите ключ (число):",
        "random_button_text": "Сгенерировать случайный ключ",
        "output_label": "Вывод:",
        "encrypt_button": "Зашифровать",
        "decrypt_button": "Расшифровать",
        "file_encryption_decryption_tool_title": "Инструмент для шифрования/расшифровки файлов",
        "select_file_label": "Выберите файл:",
        "browse_button_text": "Обзор",
        "select_encryption_method_label": "Выберите метод шифрования:",
        "enter_key_label": "Введите ключ (число):",
        "generate_random_key": "Сгенерировать случайный ключ",
        "save_file_title": "Сохранить файл",
        "file_processed_success": "Файл обработан и сохранен успешно!",
        "error": "Ошибка",
        "unknown_method_error": "Неизвестный метод.",
        "key_is_digit_error": "Ключ должен быть числом.",
        "no_file_selected": "Файл не выбран.",
        "your_key": "Ваш ключ: ",
        "browse_file_title": "Выберите файл",
        "an_error_occurred": "Произошла ошибка",
    },
    "it": {
        "title": "Strumento di crittografia/decrittografia",
        "text_label": "Inserisci testo:",
        "encryption_method_label": "Seleziona metodo di crittografia:",
        "key_label": "Inserisci chiave (numero):",
        "random_button_text": "Genera chiave casuale",
        "output_label": "Output:",
        "encrypt_button": "Crittografa",
        "decrypt_button": "Decrittografa",
        "file_encryption_decryption_tool_title": "Strumento di crittografia/decrittografia file",
        "select_file_label": "Seleziona file:",
        "browse_button_text": "Sfoglia",
        "select_encryption_method_label": "Seleziona metodo di crittografia:",
        "enter_key_label": "Inserisci chiave (numero):",
        "generate_random_key": "Genera chiave casuale",
        "save_file_title": "Salva file",
        "file_processed_success": "File elaborato e salvato con successo!",
        "error": "Errore",
        "unknown_method_error": "Metodo sconosciuto.",
        "key_is_digit_error": "La chiave deve essere un numero.",
        "no_file_selected": "Nessun file selezionato.",
        "your_key": "La tua chiave è: ",
        "browse_file_title": "Seleziona file",
        "an_error_occurred": "Si è verificato un errore",
    },
    "tr": {
        "title": "Şifreleme/Şifre Çözme Aracı",
        "text_label": "Metin Girin:",
        "encryption_method_label": "Şifreleme Yöntemi Seçin:",
        "key_label": "Anahtar Girin (Sayı):",
        "random_button_text": "Rastgele Anahtar Oluştur",
        "output_label": "Çıktı:",
        "encrypt_button": "Şifrele",
        "decrypt_button": "Şifre Çöz",
        "file_encryption_decryption_tool_title": "Dosya Şifreleme/Şifre Çözme Aracı",
        "select_file_label": "Dosya Seçin:",
        "browse_button_text": "Gözat",
        "select_encryption_method_label": "Şifreleme Yöntemi Seçin:",
        "enter_key_label": "Anahtar Girin (Sayı):",
        "generate_random_key": "Rastgele Anahtar Oluştur",
        "save_file_title": "Dosyayı Kaydet",
        "file_processed_success": "Dosya başarıyla işlenip kaydedildi!",
        "error": "Hata",
        "unknown_method_error": "Bilinmeyen yöntem.",
        "key_is_digit_error": "Anahtar bir sayı olmalı.",
        "no_file_selected": "Hiçbir dosya seçilmedi.",
        "your_key": "Anahtarınız: ",
        "browse_file_title": "Dosya Seç",
        "an_error_occurred": "Bir hata oluştu",
    },
    "ar": {
        "title": "أداة التشفير / فك التشفير",
        "text_label": "أدخل النص:",
        "encryption_method_label": "اختر طريقة التشفير:",
        "key_label": "أدخل المفتاح (رقم):",
        "random_button_text": "توليد مفتاح عشوائي",
        "output_label": "الإخراج:",
        "encrypt_button": "تشفير",
        "decrypt_button": "فك التشفير",
        "file_encryption_decryption_tool_title": "أداة تشفير / فك تشفير الملفات",
        "select_file_label": "اختر ملف:",
        "browse_button_text": "تصفح",
        "select_encryption_method_label": "اختر طريقة التشفير:",
        "enter_key_label": "أدخل المفتاح (رقم):",
        "generate_random_key": "توليد مفتاح عشوائي",
        "save_file_title": "حفظ الملف",
        "file_processed_success": "تم معالجة الملف وحفظه بنجاح!",
        "error": "خطأ",
        "unknown_method_error": "طريقة غير معروفة.",
        "key_is_digit_error": "يجب أن يكون المفتاح رقمًا.",
        "no_file_selected": "لم يتم اختيار ملف.",
        "your_key": "مفتاحك هو: ",
        "browse_file_title": "اختر ملف",
        "an_error_occurred": "حدث خطأ",
    },
    "zh": {
        "title": "加密/解密工具",
        "text_label": "请输入文本：",
        "encryption_method_label": "选择加密方法：",
        "key_label": "输入密钥（数字）：",
        "random_button_text": "生成随机密钥",
        "output_label": "输出：",
        "encrypt_button": "加密",
        "decrypt_button": "解密",
        "file_encryption_decryption_tool_title": "文件加密/解密工具",
        "select_file_label": "选择文件：",
        "browse_button_text": "浏览",
        "select_encryption_method_label": "选择加密方法：",
        "enter_key_label": "输入密钥（数字）：",
        "generate_random_key": "生成随机密钥",
        "save_file_title": "保存文件",
        "file_processed_success": "文件处理并成功保存！",
        "error": "错误",
        "unknown_method_error": "未知方法。",
        "key_is_digit_error": "密钥必须是数字。",
        "no_file_selected": "没有选择文件。",
        "your_key": "您的密钥是：",
        "browse_file_title": "选择文件",
        "an_error_occurred": "发生错误",
    },
    "no": {
        "title": "Kryptering/Dekryptering Verktøy",
        "text_label": "Skriv inn tekst:",
        "encryption_method_label": "Velg krypteringsmetode:",
        "key_label": "Skriv inn nøkkel (nummer):",
        "random_button_text": "Generer tilfeldig nøkkel",
        "output_label": "Utdata:",
        "encrypt_button": "Krypter",
        "decrypt_button": "Dekrypter",
        "file_encryption_decryption_tool_title": "Fil kryptering/dekryptering verktøy",
        "select_file_label": "Velg fil:",
        "browse_button_text": "Bla gjennom",
        "select_encryption_method_label": "Velg krypteringsmetode:",
        "enter_key_label": "Skriv inn nøkkel (nummer):",
        "generate_random_key": "Generer tilfeldig nøkkel",
        "save_file_title": "Lagre fil",
        "file_processed_success": "Fil behandlet og lagret!",
        "error": "Feil",
        "unknown_method_error": "Ukjent metode.",
        "key_is_digit_error": "Nøkkelen må være et nummer.",
        "no_file_selected": "Ingen fil valgt.",
        "your_key": "Din nøkkel er: ",
        "browse_file_title": "Velg fil",
        "an_error_occurred": "En feil oppstod",
    },
    "ge": {
        "title": "შეფერის/გაშიფვრის ხელსაწყო",
        "text_label": "შეიყვანეთ ტექსტი:",
        "encryption_method_label": "აირჩიეთ შიფრაციის მეთოდი:",
        "key_label": "შეიყვანეთ გასაღები (რაოდენობა):",
        "random_button_text": "შექმენით შემთხვევითი გასაღები",
        "output_label": "გამოსავალი:",
        "encrypt_button": "შეფერე",
        "decrypt_button": "გაშიფრე",
        "file_encryption_decryption_tool_title": "ფაილების შიფრაციის/გაშიფვრის ხელსაწყო",
        "select_file_label": "აირჩიეთ ფაილი:",
        "browse_button_text": "მოძიება",
        "select_encryption_method_label": "აირჩიეთ შიფრაციის მეთოდი:",
        "enter_key_label": "შეიყვანეთ გასაღები (რაოდენობა):",
        "generate_random_key": "შექმენით შემთხვევითი გასაღები",
        "save_file_title": "შენახვა",
        "file_processed_success": "ფაილი წარმატებით დამუშავდა და შეინახა!",
        "error": "შეცდომა",
        "unknown_method_error": "უცნობი მეთოდი.",
        "key_is_digit_error": "გასაღები უნდა იყოს რიცხვი.",
        "no_file_selected": "ფაილი არ არის არჩეული.",
        "your_key": "თქვენი გასაღებია: ",
        "browse_file_title": "აირჩიეთ ფაილი",
        "an_error_occurred": "შეცდომა მოხდა",
    },
    "so": {
        "title": "Qalabka Qarsoodiga/Ka-dejinta Qarsoodiga",
        "text_label": "Geli qoraalka:",
        "encryption_method_label": "Xulo Habka Qarsoodiga:",
        "key_label": "Geli Furaha (Nambarka):",
        "random_button_text": "Abuur Furaha Aan Caadi Ahayn",
        "output_label": "Natiijada:",
        "encrypt_button": "Qarsoodi",
        "decrypt_button": "Ka-deji",
        "file_encryption_decryption_tool_title": "Qalabka Qarsoodiga/Ka-dejinta Qarsoodiga ee Faalada",
        "select_file_label": "Xulo Faalad:",
        "browse_button_text": "Raadi",
        "select_encryption_method_label": "Xulo Habka Qarsoodiga:",
        "enter_key_label": "Geli Furaha (Nambarka):",
        "generate_random_key": "Abuur Furaha Aan Caadi Ahayn",
        "save_file_title": "Keydi Faalada",
        "file_processed_success": "Faalada waa la farsameeyey oo si guul leh loo kaydiyey!",
        "error": "Khalad",
        "unknown_method_error": "Hab aan la aqoon.",
        "key_is_digit_error": "Furaha waa inuu noqdaa nambor.",
        "no_file_selected": "Faalad lama xushay.",
        "your_key": "Furahaaga waa: ",
        "browse_file_title": "Xulo Faalada",
        "an_error_occurred": "Khalad ayaa dhacay",
    },
}